channels = ["anaconda", "conda-forge"]

[deps]
python = ""

[pip.deps]
urllib3 = ">=1.25.4"
amazon-braket-pennylane-plugin = ""
amazon-braket-sdk = ""
pennylane = ""
pennylane-qiskit = ""
openfermionpyscf = ""
